#!/bin/sh

for package in "llvm";
do
#  echo $package
  n=`find ${arch} -name init.sh | grep /${package}/ | wc -l`
  if [ $n -ne "1" ]
     then
     echo "Cant figure out ${package} version. help..."
     exit 1
  fi
  source `find ${arch} -name init.sh | grep /${package}/` 
done


modularize $@
